### ISSUE TITLE
Consul and Terraform

### ISSUE THREAD

**Issue by linuxbsdfreak** [kube-champ/terraform-operator#5]
I like the concept of terraform operator. I had the following questions:

- How can terrafrom modules pickup its configuration values from Consul when used via the operator way? 

Similar to the example defined here 

https://github.com/ned1313/terraform-tuesdays/tree/017f5bd976f91e33513ed2c885866d6f654a29f1/2020-06-02-ConsulDataSource

- Also i am using vault and terraform. How can i use a vault token in the crd to contact vault via terraform ?

**Comment by IbraheemAlSaady** [comment]
Hello @linuxbsdfreak, first of all, thank you playing around with the operator and for being the first issue :)

The idea behind the operator is that you already have your modules, but you just need to run them in Kubernetes. Based on the example you provided, you need to create a module that has the following code:

```terraform
#######################################################################################
# DATA SOURCE
#######################################################################################

data "consul_keys" "networking" {
  key {
    name    = "vpc_cidr"
    path    = "terraform/vpc/${terraform.workspace}/cidr_range"
    default = "10.3.0.0/16"
  }
}

#######################################################################################
# OUTPUTS
#######################################################################################

output "vpc_cidr" {
  value = data.consul_keys.networking.var.vpc_cidr
}
```

Say you created and published the module to your git repo, the way you would use it in the operator is as follows:


```yaml
apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: consul-module
spec:
  terraformVersion: 1.0.2. # <-- change this to your target version

  module:
    source: https://github.com/your-org/your-module-repo.git # <-- assuming the root has the terraform code 

  workspace: prod # <-- change this to your target workspace name

  providersConfig: | 
    provider "consul" {
      address    = "127.0.0.1:8500"
      datacenter = dc1
    }

  outputs:
    - key: vpc_cidr # <-- a secret will be created that has key 'vpc_cidr' with the value 
      moduleOutputName: vpc_cidr
```

## Using Vault

For the vault, let's assume you also have your terraform code somewhere on git, same as above, you would do the following

 ```yaml
apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: vault-module
spec:
  terraformVersion: 1.0.2. # <-- change this to your target version

  module:
    source: https://github.com/your-org/your-vault-module-repo.git # <-- assuming the root has the terraform code 
  
  providersConfig: | 
    provider "vault" {}

  variables:
    - key: VAULT_ADDR
       value: "your_vault_address"
       environmentVariable: true
    - key: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-credentials
          key: token
      environmentVariable: true
```

The variables defined above are environment variables to authenticate vault according to the [terraform vault docs](https://registry.terraform.io/providers/hashicorp/vault/latest/docs)

Please let me know if I can assist you more or if you have any more questions

**Comment by linuxbsdfreak** [comment]
Thanks  @IbraheemAlSaady  for the clarifications. I have the following code snippet in a TF module
 
`provider "vault" {
  alias   = "bootstrap"
  address = local.vault_address
  namespace = join("/", [local.vault_base_namespace, local.vault_bootstrap_namespace])
  auth_login {
    path      = "auth/jenkins_ci/login"
    namespace = local.vault_base_namespace
    parameters = {
      role_id   = var.login_approle_role_id
      secret_id = var.login_approle_secret_id
    }
  }
}

provider "consul" {
  address    = "${var.consul_address}:${var.consul_port}"
  datacenter = var.consul_datacenter
  token      = var.consul_token
}
`

How can i offload the consul_token and login_approle_role_id/login_approle_secret_id  as a secret in K8s and reference it to the module in the CR? 

May be you should have some examples in the repo with different scenarios for better understanding. 

Also the links within https://github.com/kube-champ/terraform-operator/blob/master/config/samples/README.md are broken

**Comment by IbraheemAlSaady** [comment]
@linuxbsdfreak thanks for pointing out the broken links, I'm pushing a fix for that. I will also include consul and vault examples for future users

Back to your issue, most of the Terraform providers accept environment variables for sensitive data

For consul, according to the [providers docs](https://registry.terraform.io/providers/hashicorp/consul/latest/docs#token) token can be specified with `CONSUL_HTTP_TOKEN` or `CONSUL_TOKEN` as an environment variable. That means you can offload it with the CR like this

```yaml
apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
 name: vault-module
spec:
  ....
  providersConfig: |
    provider "consul" {
      address    = "127.0.0.1:8500"
      datacenter = "dc1"
    }

  variables:
    - key: CONSUL_TOKEN
      valueFrom:
        secretKeyRef:
          name: consul-credentials
          key: token
      environmentVariable: true
```
You must have a Kubernetes secret in the same namespace where you're creating the `Terraform` object. `kubectl create secret generic consul-credentials --from-literal=token=YOUR_CONSUL_TOKEN`

For **Vault** it's a different story, according to the [Providers docs](https://registry.terraform.io/providers/hashicorp/vault/latest/docs) you can not specify the `login_approle_role_id` and `login_approle_secret_id` as environment variables. Currently it has to be in plain text in the `spec.providersConfig` section
of the CR

```yaml
apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
 name: vault-module
spec:
  ....
  providersConfig: |
    provider "vault" {
      alias   = "bootstrap"
      namespace = "ns1/ns2" # <-- you can also use VAULT_NAMESPACE env variable
      auth_login {
        path      = "auth/jenkins_ci/login"
        namespace = "your_base_namespace"
        parameters = {
          role_id   = "rol_id"
          secret_id = "role_secret_id"
        }
      }
    }

  variables:
    - key: VAULT_ADDR
      value: "the vault address"
      # valueFrom: # <-- you can also get the address from a secret key just like the consul token
      environmentVariable: true
```

**Comment by linuxbsdfreak** [comment]
Thx @IbraheemAlSaady for providing detailed information and also fixing the links. I had one more query. 

```
locals {
  flux_install   = var.flux_install != null ? var.flux_install : jsondecode(data.consul_keys.shoot_cluster_setup.var.shoot_cluster_setup)["flux_install"]
  argocd_install = var.argocd_install != null ? var.argocd_install : jsondecode(data.consul_keys.shoot_cluster_setup.var.shoot_cluster_setup)["argocd_install"]
}

module "vault-shoot-setup" {
  source           = "./../modules/vault-shoot-setup"
  cluster_name     = var.cluster_name
  gardener_project = var.gardener_project

  providers = {
    vault.bootstrap  = vault.bootstrap
    kubernetes.shoot = kubernetes.shoot
    kubernetes.robot = kubernetes.robot
  }
}

module "vault-operator" {
  source           = "./../modules/vault-operator"
  cluster_name     = var.cluster_name
  gardener_project = var.gardener_project

  providers = {
    vault.bootstrap  = vault.bootstrap
    kubernetes.shoot = kubernetes.shoot
    helm.shoot       = helm.shoot
  }
  depends_on = [module.vault-shoot-setup]
}

module "fluxv2-bootstrap" {
  source           = "./../modules/fluxv2-bootstrap"
  cluster_name     = var.cluster_name
  gardener_project = var.gardener_project

  providers = {
    kubectl.shoot    = kubectl.shoot
    kubernetes.shoot = kubernetes.shoot
    github.gitops    = github.gitops
    flux.gitops      = flux.gitops
  }
}
```
I am consuming the modules as shown above and trying to make a module depend on another module as shown with the **depends_on**.  Is this possible to configure that via the CRD  ?

**Comment by IbraheemAlSaady** [comment]
Hi @linuxbsdfreak, at this moment, dependencies on Terraform you define through the CR is not possible, however, its the first thing on the roadmap, and I will pick it up today

What you can do for now is publish the above code as a module, either on terraform registry (publish) or just push it to your git repo (can be private repo). And then in the CR provide the `source` inside the `module` definition

If your git repo is private, you need to provide the SSH key so you can authenticate the `terraform-runner` to your git. Check this [example](https://github.com/kube-champ/terraform-operator/blob/master/config/samples/terraform-git-ssh.yaml)

**Comment by linuxbsdfreak** [comment]
Thx @IbraheemAlSaady . That means i will have to package the above snippet in a module and refer as a source as shown below 

```
 module:
   source: https://github.com/your-org/calling-module-repo.git 
```

I will have to also change the path within the root module 

```
source           = "./../modules/fluxv2-bootstrap"
```
to 
```
source           = "https://github.com/your-org/modules/fluxv2-bootstrap"
```

Is that correct ?

**Comment by IbraheemAlSaady** [comment]
@linuxbsdfreak as an example, you can create the module by just creating a single `tf` file (say `main.tf`) with the content of your above snippet and push it to your git

let's take [this example](https://github.com/kube-champ/terraform-k8s-flux-bootstrap.git). Its a terraform module that bootstraps a cluster with Fluxv2 and SealedSecrets

Then in my CR object, I can just do this

```yaml
apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
 name: flux-module
spec:
  ....
  module:
    source: "https://github.com/kube-champ/terraform-k8s-flux-bootstrap.git"
```

Since the `terraform-k8s-flux-bootstrap` module accepts a variable called `git_url` as stated [here](https://github.com/kube-champ/terraform-k8s-flux-bootstrap/blob/master/variables.tf), then in the CR I can pass that variable like this

```yaml
kind: Terraform
....
spec:
  ...
  variables:
     - key: git_url
       value: my_git_repo
```

If the module you publish uses local modules like what you have in your case 

```
source           = "./../modules/fluxv2-bootstrap"
```

You don't need to change that, although you can, but you don't need to. 

So in your case, you can do the following:

1. Create an empty git repo
2. Create the required tf files in the root
3. You can create a `modules` directory for local modules
4. In the Terraform CR, point the source to that git repo and put the correct providersConfig

I hope that's clear
